/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class www_mys_com_sbjni_utils_NativeUtils */

#ifndef _Included_www_mys_com_sbjni_utils_NativeUtils
#define _Included_www_mys_com_sbjni_utils_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     www_mys_com_sbjni_utils_NativeUtils
 * Method:    getJniStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_www_mys_com_sbjni_utils_NativeUtils_getJniStr
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
